## ملف الدوكر هذا بيجي ك يوتيلز عشان اقدر اسوي منج للكونتينرات حقاتي بشكل احسن
## هي تيجي مع دوكر ولكن مو من ضمن دوكر هي منفصله عنه ، بيكون دوكر اله اصدار ودوكر كومبوز اله اصدار ثاني

## طبعا دوكر كومبوس تبان استخدامه اكثر لما يكون عندي اكثر من كونتينر بكلمو بعض

## مثلا لما كنا نسوي رن للكونتينر عندنا كنا اول شي نسوي بيلد وبيعدها نسوي كونتينر من الاميج الي سويناها
## كنا نكتب اوامر كبيره مع دوكر كومبوز بيختصر كل شي لك 
## الان نبدا كتابته

## نحط هنا اصدار الدكر كومبوز الي بدنا نستخدمه ولكن يجب ان يتناسب مع اصدار الدوكر الي عندك
##   وعشان تشوف تناسب اصدار الدوكر والدكور كمبوس بتلاقي كل شي هنا
version: "3"

## الحين نبدا نعرف السيرفيسيس نقدر نقول انه ايش الكونتينرز الي عندك
services:
##  الحين نبدا نعرف كل السيرفيسيس حقتي او الستيبس
  node-app: ## هيك نحط اسم اله
  ## اللحين نبدا نعرف بعض الحاجات لابلكيشن هذا وهذا الشي هيساعدني ما اكتب دايم الاوامر الكبيره
  ## docker run --name express-node-app-container -v $(pwd)/src:/app/src:ro -d -p 4000:4000 express-node-app الحين نقعد نفكفك الامر هذا
    container_name: express-node-app-container ## اول شي نحدد اسم الكونتينر 
    ##  هنا نحدد من وين ملف الدوكر فايل الي راح يسوي منها اميج ان حطينا نقطه لحاله راح يدور على ملف الدوكر فايل
    build: . ##    ويسوي بيلد منه طبعا بيحط له اسمه لاميج بشكل اوتاميتك ياخذ اسم الفايل الي انت فيه وجنبه اسم السيرفيس
    volumes: ## الحين نكتب الفوليوم الي استخدمناهم وهنا استخدمنا فقط البايند
      - ./src:/app/src:ro ## لانه احنا جوا ملف جوا المشروع $(pwd) بدل  ./src الحين نعمل عمليه البايندج وهنا نقدر نستخدم 
    ports:  ## اللحين اجا دور البورت
      - "4000:4000"
    environment: ## Environment Variables هيك نرسل 
      - PORT=4000
      - NODE_ENV=production 
    ## Environment Variables لو كان عددهم كثير بقدر ارسل الملف كامل حق الانف وفيه كل
    ## env_file:
    ## - ./.env 


    ## Environment Variables بفيديو اليوم هنتعلم كيف اباس متغيرات للكونتينر حقي 
    ## Production ي غير لو هييرن في Development او كيف استخدم دوكر عشان اسوي اداره لبيئات مختلفه للبرنامج حقي لانه لو هييرن في ال التيستنج غير لما هيييرن في 
    ## مثلا هنرسل رقم البورت كمبتغير << تكمله الشرح في صفحة الانديكس