version: "3"

services:
  node-app: 
    container_name: express-node-app-container 
    build: .
    ports:  
      - "4000:4000"
    env_file:
      - ./.env
    depends_on: ## هذا الشي بحطه انه بقوله لا تشتغل هذا السيرفيس الا بعد ما تشتغل سيرفس المونجو 
      - mongo
  ##اليوم هنتعلم كيف اضيف سيرفس ثانيه تمثل كقاعده بيانات السيرفس الاولى النود كانت هذي الابلكيشن اللحين بنسوي كومنتينر الي يمثل قاعده البيانات
  mongo:
    image: mongo ## هنا ما حطينا بيلد مثل فوق والسبب هنا جاهز الاميج موجود في دوكر هب مو لازم اسوي واحد بنفسي
    restart: always
    volumes:  ## mongo-db هنا ما يقصد فيها مكان لربط الفوليوم عندي لوكال ولكن فقط عشان يحفظ بياناتي بالدوكر بلمف اسمه داتا سلاش دي بي
      - mongo-db:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
  mongo-express: ## لقاعده بيانات المونجو الي استخدمناها بالاميج الي فوق UI tools هذي اميج تعطيني  
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on: ## نفس الشي هذا بدي اياه يشتغل بعد  ما تشتغل قاعده البيانات
      - mongo
  redis:
    image: redis

volumes: ## نكتب الفوليوم هنا عشان لما ينشاه يحط له اسمه مو اسم عشوائي وبعديها نستدعيها فوق
  mongo-db: 